apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://10.5.0.5:9090
    isDefault: true
  - name: mysql
    type: mysql
    access: proxy
    url: 10.5.0.4:3306
    database: fluentd
    user: root
    secureJsonData:
      password: fluentd
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    isDefault: false
