{
 "title": "Node Exporter",
 "description": "node_exporter dashboard with docker stats",
 "tags": [
  "Prometheus",
  "node_exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total"
    }
   ]
  },
  {
   "title": "Docker container running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "{{ instance }}-{{ state }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "description": "Network Throughput (RX+TX combined)",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8)+sum(irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8)"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})",
     "legendFormat": "Percent {{instance}}：{{mountpoint}}"
    },
    {
     "expr": "1-(predict_linear(node_filesystem_free_bytes{fstype=~\"ext4|xfs\"}[1d], 24*3600) / node_filesystem_size_bytes{fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}  (+24h prediction)"
    },
    {
     "expr": "node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}  ",
     "legendFormat": "Disk space free: {{instance}}：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT4/XFS)",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=~'$node',fstype=~\"ext.*|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\"})"
    },
    {
     "expr": "(1-((predict_linear(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\"}[24h],24*3600)) / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\"})) - (1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\"}))"
    },
    {
     "expr": "predict_linear(node_filesystem_avail_bytes{instance=~'$node',fstype=~\"ext.*|xfs\"}[24h],24*3600)"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "timeseries",
   "description": "Read/write completions per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_Avaliable"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "timeseries",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[30m]) / irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[30m]) / irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Write time"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "timeseries",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "{{instance}}_CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "{{instance}}_Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
     "legendFormat": "{{instance}}_UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_alloc"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}",
     "legendFormat": "filefd_{{instance}}"
    },
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[30m])",
     "legendFormat": "switches_{{instance}}"
    }
   ]
  },
  {
   "title": "Hardware Temperature(VM may not display the metrics)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~'$node'}",
     "legendFormat": "{{instance}}_{{chip}}_{{sensor}}"
    }
   ]
  }
 ]
}