- name: Выдаем права скрипту для теста
  ansible.builtin.file:
    path: files/test.sh
    mode: '0755'
    owner: root
    group: root
- name: Запускаем тест
  ansible.builtin.shell: bash -x ./files/test.sh
  args:
    executable: /bin/bash
  register: test_output
  failed_when: false
  changed_when: false
  timeout: 120
- name: Результаты теста
  ansible.builtin.debug:
    var: test_output.stdout_lines
- name: Проверяем ошибки теста
  ansible.builtin.fail:
    msg: "Скрипт завершился с ошибкой. Вывод: {{ test_output.stderr }}"
  when: test_output.rc != 0
