scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.5.0.8:9100']
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.5.0.9:9113']
  - job_name: 'mysql'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.5.0.10:9104']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.5.0.11:8080']
